### PR TITLE
builder API, op_return, multi-dest address support

### PR DESCRIPTION
**Pull request by mvayngrib**
kind of a general rehaul, so you probably won't be interested in merging this. I'm using it in my [fork](https://github.com/mvayngrib/bitcoin-faucet) of your bitcoin-faucet though, so thought I'd put it out there.

I ended up going with bitcoinjs-lib (for now). No time atm to convert the project i'm working on to your more modular libs.

### CODE REVIEW

**Comment by jprichardson** [comment]
Very cool. Did a preliminary glance... looks good. I'll review more thoroughly later tonight or tomorrow.

**Comment by mvayngrib** [comment]
great, let me know :)

**Comment by jprichardson** [comment]
Ok, I'm going to have to defer this. When I glanced over it, it looked pretty solid. Love the fluent interface. It's just that the PR is too big for me to make it a priority to review at the moment. I will get to it though :)

**Comment by mvayngrib** [comment]
i understand, no problem

**Pull request closed without merging**
